### ISSUE TITLE
java.nio.file.NoSuchFileException in .mcool

### ISSUE THREAD

**Issue by MarcoDiS** [PouletAxel/SIP#19]
Can you help me to solve the following problem?

INPUT:
I am trying to call loops on a .mcool file from micro-C in dm6 with observed and balanced entries at resolutions 100, 400 and 800 base-pairs, which I checked using cooltools:
['/resolutions/100', '/resolutions/400', '/resolutions/800'].

_chrom_sizes.txt_:
chr3L	28110227
chr3R	32079331
chr2L	23513712
chr2R	25286936
chrX	23542271
chrY	3667352
chrM	19524
chr4	1348131

COMMAND:
java -jar SIP_HiC_v1.6.1.jar cool my_data.mcool chrom_sizes.txt SIP_output /usr/bin/cooltools /usr/bin/cooler -isDroso false -res 400 -factor 2 -t 2000 -fdr 0.1 -d 15 -mat 5000 -nbZero 6 -del true -cpu 8 -g 3 -min 2 -max 2

OUTPUT (first part):
cooltools, version 0.5.1

cooler, version 0.8.11

cool mode: 
input: my_data.mcool
output: SIP_output
cooltools: /usr/bin/cooltools
cooler: /usr/bin/cooler
norm: KR
gauss: 3.0
min: 2.0
max: 2.0
matrix size: 5000
diag size: 15
resolution: 400
saturated pixel: 0.01
threshold: 2000
number of zero :6
factor 2
fdr 0.1
del true
cpu 8
-isDroso false

start SIP_output/400kb.expected
Start cooltools compute-expected
java.nio.file.NoSuchFileException: SIP_output/400kb.expected
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at java.nio.file.Files.newBufferedReader(Files.java:2784)
	at utils.CoolerExpected.parseExpectedFile(CoolerExpected.java:90)
	at utils.CoolerExpected.dumpExpected(CoolerExpected.java:79)
	at multiProcesing.ProcessCoolerDumpData.go(ProcessCoolerDumpData.java:61)
	at sipMain.Hic_main.main(Hic_main.java:280)
!!!!!!! End SIP_output/400kb.expected
...

COMMENT:
It seems it is looking for a resolution of 400kb, which I never asked for, and (of course) it is not present in the input.
It does the same for 800kb since my _factor_ parameter is 2.
Additionally, it is looking for 'KR' normalization, which I think is what a _.hic_ file may have, but not a _.mcool_.

**Comment by PouletAxel** [comment]
Hi,

the same question was asked in the in the issue #18
can you try if  using cooler=0.8.6, cooltools=0.3.2 solved your problem?
I will close your issue you can answer then in the issue #18 

Thanks 
Axel
