### ISSUE TITLE
sip stalling

### ISSUE THREAD

**Issue by avramiaharonoff** [PouletAxel/SIP#20]
Hello,

Thanks for your tool! It's great. I'm running into a snag where the program stalls during the loop calling step.

For example, it stalls here, or at a later time.

Start loop detction step
./5kb/chrI/
./5kb/normVector/chrI.normnormVector end loading file: chrI.norm 5kb
2 ./5kb/chrI/chrI_2500000_4999999.txt
1 ./5kb/chrI/chrI_1250000_3749999.txt

I'm not really sure why, and no error pops up, just stalls until the time I requested runs out.

I am using v1.6.2 and juicer tools v1.13.01 like recommended. The weird thing is it was working for a while before it started stalling.

 Thank you,

Avrami

**Comment by PouletAxel** [comment]
Hi Avrami,
Could you send me the command line or the parameters you used please?
Best
Axel

**Comment by jiangshan529** [comment]
> Hi Avrami, Could you send me the command line or the parameters you used please? Best Axel

Hi, I meet the same problem, it stalls: Start loop detction step
./WT_SIP/5kb/chr9/
./WT_SIP/5kb/normVector/chr9.normnormVector end loading file: chr9.norm 5kb
12 ./WT_SIP/5kb/chr9/chr9_60000000_69999999.txt
2 ./WT_SIP/5kb/chr9/chr9_10000000_19999999.txt
10 ./WT_SIP/5kb/chr9/chr9_50000000_59999999.txt
0 ./WT_SIP/5kb/chr9/chr9_0_9999999.txt,

the command I used is: java -jar ~/biosoft/SIP_HiC_v1.6.1.jar hic HEK_WT1_merge_UU_dedup.pairs.hic /genome_sequence/human/hg38/hg38.clean.chrom.sizes ./WT_SIP ~/juicer/CPU/common/juicer_tools.jar

**Comment by PouletAxel** [comment]
Hi,
Could you send me the version of juicer_tools that you are using please?
Best

Axel

**Comment by jiangshan529** [comment]
> ~/juicer/CPU/common/juicer_tools.jar

hi, it is juicer_tools.1.9.9_jcuda.0.8.jar

**Comment by PouletAxel** [comment]
Thanks,
I will run SIP on HiC data with the same parameter, I will come back to you later

**Comment by PouletAxel** [comment]
can you try to run: SIP_HiC_v1.6.1.jar version please. It is working for me.
So if you need result now you can use this version.
I will work on a new version as soon as possible sorry about that

Best
Axel

**Comment by PouletAxel** [comment]
[jiangshan529](https://github.com/jiangshan529) could you test the new version of SIP I just pre-released (https://github.com/PouletAxel/SIP/releases). I tested on my laptop, running different datasets and it didn't stale and I obtain the usual output.

I will wait your feedback before to made this version a real release

**Comment by jiangshan529** [comment]
> [jiangshan529](https://github.com/jiangshan529) could you test the new version of SIP I just pre-released (https://github.com/PouletAxel/SIP/releases). I tested on my laptop, running different datasets and it didn't stale and I obtain the usual output.
> 
> I will wait your feedback before to made this version a real release

Hi, Thank you! I downloaded the jar file and it reports some error: 
$ java -jar SIP-1.6.4.jar
Exception in thread "main" java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
	at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:208)
	at java.desktop/java.awt.Window.<init>(Window.java:548)
	at java.desktop/java.awt.Frame.<init>(Frame.java:423)
	at java.desktop/java.awt.Frame.<init>(Frame.java:388)
	at java.desktop/javax.swing.JFrame.<init>(JFrame.java:180)
	at plop.gui.GuiAnalysis.<init>(GuiAnalysis.java:136)
	at plop.sipMain.Hic_main.main(Hic_main.java:186)

**Comment by PouletAxel** [comment]
Can you tell me how are you running the program please,
only to help to pinpoint the problem.

**Comment by PouletAxel** [comment]
Did you only run java -jar SIP-1.6.4.jar in the terminal?
If yes he is trying to open a graphical user interface,
can you run:
java -jar SIP-1.6.4.jar -h

**Comment by jiangshan529** [comment]
> Did you only run java -jar SIP-1.6.4.jar in the terminal? If yes he is trying to open a graphical user interface, can you run: java -jar SIP-1.6.4.jar -h

thanks. there are some other problems:
##### End dump chr14 10kb
start dump chr17 size 83257441 dump chr17:70000000:83257441 res 10kb
##### End dump chr17 10kb
########### End of the dump Step
Start loop detection step
./HCT_SIP/10kb/chr9/
./HCT_SIP/10kb/normVector/chr9.normnormVector end loading file: chr9.norm 10kb
./HCT_SIP/10kb/chr7/
./HCT_SIP/10kb/normVector/chr7.normnormVector end loading file: chr7.norm 10kb
./HCT_SIP/10kb/chr8/
./HCT_SIP/10kb/normVector/chr8.normnormVector end loading file: chr8.norm 10kb
./HCT_SIP/10kb/chr5/
./HCT_SIP/10kb/normVector/chr5.normnormVector end loading file: chr5.norm 10kb
./HCT_SIP/10kb/chr6/
./HCT_SIP/10kb/normVector/chr6.normnormVector end loading file: chr6.norm 10kb
./HCT_SIP/10kb/chr21/
./HCT_SIP/10kb/normVector/chr21.normnormVector end loading file: chr21.norm 10kb
./HCT_SIP/10kb/chr3/
./HCT_SIP/10kb/normVector/chr3.normnormVector end loading file: chr3.norm 10kb
./HCT_SIP/10kb/chr22/
./HCT_SIP/10kb/normVector/chr22.normnormVector end loading file: chr22.norm 10kb
2	./HCT_SIP/10kb/chr8/chr8_20000000_39999999.txt
0	./HCT_SIP/10kb/chr22/chr22_0_19999999.txt
7	./HCT_SIP/10kb/chr3/chr3_70000000_89999999.txt
0	./HCT_SIP/10kb/chr21/chr21_0_19999999.txt
1	./HCT_SIP/10kb/chr9/chr9_10000000_29999999.txt
11	./HCT_SIP/10kb/chr6/chr6_110000000_129999999.txt
10	./HCT_SIP/10kb/chr7/chr7_100000000_119999999.txt
1	./HCT_SIP/10kb/chr5/chr5_10000000_29999999.txt
Exception in thread "pool-2-thread-6" java.lang.NoClassDefFoundError: Could not initialize class ij.plugin.frame.Recorder
	at ij.ImagePlus.getProcessor(ImagePlus.java:986)
	at ij.ImagePlus.createLut(ImagePlus.java:1679)
	at ij.ImagePlus.getFileInfo(ImagePlus.java:2436)
	at ij.io.FileSaver.<init>(FileSaver.java:36)
	at plop.process.CallLoops.saveFile(CallLoops.java:171)
	at plop.process.CallLoops.makeImage(CallLoops.java:157)
	at plop.process.CallLoops.detectLoops(CallLoops.java:96)
	at plop.multiProcesing.RunnableDetectLoops.run(RunnableDetectLoops.java:87)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Exception in thread "pool-2-thread-8" java.lang.ExceptionInInitializerError
	at ij.ImagePlus.getProcessor(ImagePlus.java:986)
	at ij.ImagePlus.createLut(ImagePlus.java:1679)
	at ij.ImagePlus.getFileInfo(ImagePlus.java:2436)
	at ij.io.FileSaver.<init>(FileSaver.java:36)
	at plop.process.CallLoops.saveFile(CallLoops.java:171)
	at plop.process.CallLoops.makeImage(CallLoops.java:157)
	at plop.process.CallLoops.detectLoops(CallLoops.java:96)
	at plop.multiProcesing.RunnableDetectLoops.run(RunnableDetectLoops.java:87)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
	at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:208)
	at java.desktop/java.awt.TextComponent.<init>(TextComponent.java:134)
	at java.desktop/java.awt.TextArea.<init>(TextArea.java:258)
	at java.desktop/java.awt.TextArea.<init>(TextArea.java:162)
	at ij.plugin.frame.Recorder.<clinit>(Recorder.java:33)
	... 11 more
this is the command I used:
java -jar SIP-1.6.4.jar hic dedup_941M.hic hg38.clean.chrom.sizes ./HCT_SIP juicer_tools.jar -cpu 8 -res 10000.
and in the output folder I did not see the loop file

**Comment by PouletAxel** [comment]
Can you share with me your hic file, and your chr file
Because I am not able to reproduce your error.

Thanks

**Comment by jiangshan529** [comment]
> Can you share with me your hic file, and your chr file Because I am not able to reproduce your error.
> 
> Thanks

Hi, this hic file is 2.9Gb, how should I share it with you?

**Comment by PouletAxel** [comment]
Via Google drive  my email is ***@***.*** or ***@***.*** from my iPhoneOn Jul 2, 2024, at 6:13 PM, jiangshan529 ***@***.***> wrote:﻿

Can you share with me your hic file, and your chr file Because I am not able to reproduce your error.
Thanks

Hi, this hic file is 2.9Gb, how should I share it with you?

**Comment by jiangshan529** [comment]
![image](https://github.com/PouletAxel/SIP/assets/75197626/9207027d-ca1e-4a4f-876e-1776bc9ee39b)

**Comment by PouletAxel** [comment]
you can find the email address here: https://github.com/PouletAxel/SIP
