### ISSUE TITLE
java.lang.NumberFormatException

### ISSUE THREAD

**Issue by Jiangyuan-Liu** [PouletAxel/SIP#24]
Hi,

I got the following error messages when I ran  "java -jar SIP-1.6.4.jar cool". Thanks.
```
Exception in thread "main" java.lang.NumberFormatException: For input string: "(/home/jiangyuan"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
        at java.base/java.lang.Integer.parseInt(Integer.java:588)
        at java.base/java.lang.Integer.parseInt(Integer.java:685)
        at plop.sipMain.Hic_main.testTools(Hic_main.java:532)
        at plop.sipMain.Hic_main.main(Hic_main.java:287)
```

I created a conda env as shown below:
```
conda create -n SIP cooler=0.8.6 cooltools=0.3.2
conda activate SIP
conda install -c conda-forge openjdk
```

```
> java -version
openjdk version "22.0.1-internal" 2024-04-16
OpenJDK Runtime Environment (build 22.0.1-internal-adhoc.conda.src)
OpenJDK 64-Bit Server VM (build 22.0.1-internal-adhoc.conda.src, mixed mode, sharing)
```

It works for "java -jar SIP-1.6.4.jar -h"

```
#SIP Version 1 run with java 8

Usage:
        hic <hicFile> <chrSizeFile> <Output> <juicerToolsPath> [options]
        cool <mcoolFile> <chrSizeFile> <Output> <cooltoolsPath> <coolerPath> [options]
        processed <Directory with processed data> <chrSizeFile> <Output> [options]

Parameters:
         chrSizeFile: path to the chr size file, with the same name of the chr as in the hic file (i.e. chr1 does not match Chr1 or 1)
        -res: resolution in bp (default 5000 bp)
   
```

**Comment by PouletAxel** [comment]
Hi,
Thanks, i will try to find the solution as soon as possible.
Best
Axel

**Comment by MuhundenJ** [comment]
Hi ! Did you find a solution? I have the same issue as well !  If it works, could you share a .yaml file of your conda environment if possible?

**Comment by PouletAxel** [comment]
No, sorry not yet.
I will try to do that this week

**Comment by MuhundenJ** [comment]
Just an update. I got it to work if I downgrade numpy to version 1.23.4 (along with older versions of cooler and cooltools as mentioned above) ! Thank you for this nice tool and look forward to the updates !

**Comment by PouletAxel** [comment]
Thanks for this solution,
I will try to make it work with the updated version of cooltools and cooler
